default:
  max_threads: 8
  output_dir: results/output
  sources:
    - url: results/output/all.yml
      type: clash
    - url: https://raw.githubusercontent.com/linzjian666/chromego_extractor/main/outputs/clash_meta.yaml
      type: clash
    - url: https://raw.githubusercontent.com/peasoft/NoMoreWalls/master/list.meta.yml
      type: clash
    - url: https://raw.githubusercontent.com/free18/v2ray/main/c.yaml
      type: clash
    - url: https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/wenode.yaml
      type: clash
    - url: https://raw.githubusercontent.com/Barabama/FreeNodes/main/nodes/yudou66.yaml
      type: clash
    - url: https://raw.githubusercontent.com/ermaozi/get_subscribe/main/subscribe/clash.yml
      type: clash
    - url: https://raw.githubusercontent.com/Ruk1ng001/freeSub/main/clash.yaml
      type: clash
    - url: https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash
      type: clash
    - url: https://raw.githubusercontent.com/zhangkaiitugithub/passcro/main/speednodes.yaml
      type: clash
    - url: https://raw.githubusercontent.com/vxiaov/free_proxies/main/clash/clash.provider.yaml
      type: clash
    - url: https://raw.githubusercontent.com/mahdibland/V2RayAggregator/master/sub/sub_merge_yaml.yml
      type: clash
      max: 1024
    - url: https://nodefree.githubrowcontent.com/%Y/%m/%Y%m%d.yaml
      type: clash
      redirect: date
    - url: https://node.freeclashnode.com/uploads/%Y/%m/0-%Y%m%d.yaml
      type: clash
      redirect: date
    - url: https://node.freeclashnode.com/uploads/%Y/%m/1-%Y%m%d.yaml
      type: clash
      redirect: date
    - url: https://node.freeclashnode.com/uploads/%Y/%m/2-%Y%m%d.yaml
      type: clash
      redirect: date
    - url: https://node.freeclashnode.com/uploads/%Y/%m/3-%Y%m%d.yaml
      type: clash
      redirect: date
    - url: https://node.freeclashnode.com/uploads/%Y/%m/4-%Y%m%d.yaml
      type: clash
      redirect: date
    - url: https://v2rayshare.githubrowcontent.com/%Y/%m/%Y%m%d.yaml
      type: clash
      redirect: date
    - url: https://gitlab.com/colloq168/nodefiltrate/-/raw/main/disney?ref_type=heads
      type: clash
    - url: https://gitlab.com/colloq168/nodefiltrate/-/raw/main/filtrate?ref_type=heads
      type: clash
    - url: https://gitlab.com/colloq168/nodefiltrate/-/raw/main/netflix?ref_type=heads
      type: clash
    - url: https://gitlab.com/colloq168/nodefiltrate/-/raw/main/openai?ref_type=heads
      type: clash
    - url: https://gitlab.com/colloq168/nodefiltrate/-/raw/main/youtube?ref_type=heads
      type: clash
    - url: https://free.datiya.com/uploads/%Y%m%d-clash.yaml
      type: clash
      redirect: date
    - url: https://raw.githubusercontent.com/lagzian/SS-Collector/main/ss_clash.yaml
      type: clash
    - url: https://raw.githubusercontent.com/lagzian/SS-Collector/main/vmess_clash.yaml
      type: clash
    - url: https://raw.githubusercontent.com/lagzian/SS-Collector/main/reality_clash.yaml
      type: clash
    - url: https://raw.githubusercontent.com/lagzian/SS-Collector/main/vmess_tvc_clash.yaml
      type: clash
    - url: https://raw.githubusercontent.com/lagzian/SS-Collector/main/backup_clash.yaml
      type: clash
    - url: https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/actives_under_1000ms.yaml
      type: clash
    - url: https://raw.githubusercontent.com/MrMohebi/xray-proxy-grabber-telegram/master/collected-proxies/clash-meta/actives_under_1500ms.yaml
      type: clash
    - url: https://raw.githubusercontent.com/qianlima8888/autoClashProxy/main/list.yaml
      type: clash
    - url: https://raw.githubusercontent.com/lagzian/SS-Collector/main/VLESS/VL100.txt
      type: v2ray
    - url: https://raw.githubusercontent.com/aiboboxx/v2rayfree/main/v2
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/Mahdi0024/ProxyCollector/master/sub/proxies.txt
      type: v2ray
    - url: https://raw.githubusercontent.com/mksshare/mksshare.github.io/main/README.md
      type: v2ray
      redirect: https
      method: base64
    - url: https://raw.githubusercontent.com/mkshare3/mkshare3.github.io/main/README.md
      type: v2ray
      redirect: https
      method: base64
    - url: https://raw.githubusercontent.com/abshare/abshare.github.io/main/README.md
      type: v2ray
      method: base64
      redirect: https
    - url: https://raw.githubusercontent.com/toshare5/toshare5.github.io/main/README.md
      type: v2ray
      method: base64
      redirect: https
    - url: https://raw.githubusercontent.com/awesome-vpn/awesome-vpn/master/all
      type: v2ray
    - url: https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/roosterkid/openproxylist/main/V2RAY_RAW.txt
      type: v2ray
    - url: https://raw.githubusercontent.com/Space-00/V2ray-configs/main/config.txt
      type: v2ray
    - url: https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/hysteria2
      type: v2ray
    - url: https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/ss
      type: v2ray
    - url: https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/trojan
      type: v2ray
    - url: https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/vless
      type: v2ray
      max: 199
    - url: https://raw.githubusercontent.com/Surfboardv2ray/TGParse/main/python/vmess
      type: v2ray
    - url: https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/vless
      type: v2ray
      method: base64
      max: 199
    - url: https://raw.githubusercontent.com/mfuu/v2ray/master/merge/merge_base64.txt
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/Flik6/getNode/main/v2ray.txt
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/hysteria2
      type: v2ray
      method: base64
      max: 199
    - url: https://raw.githubusercontent.com/Leon406/SubCrawler/main/sub/share/a11
      type: v2ray
      method: base64
      max: 199
    - url: https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/hysteria
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/vmess
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/vless
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/shadowsocks
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/soroushmirzaei/telegram-configs-collector/main/protocols/reality
      type: v2ray
      method: base64
    # - url: https://raw.githubusercontent.com/mheidari98/.proxy/main/all
    #   type: v2ray
    #   method: base64
    - url: https://t.me/s/PrivateVPNs
      type: v2ray
      method: telegram
    - url: https://t.me/s/VlessConfig
      type: v2ray
      method: telegram
    - url: https://t.me/s/proxystore11
      type: v2ray
      method: telegram
    - url: https://t.me/s/DirectVPN
      type: v2ray
      method: telegram
    - url: https://t.me/s/VmessProtocol
      type: v2ray
      method: telegram
    - url: https://t.me/s/MsV2ray
      type: v2ray
      method: telegram
    - url: https://t.me/s/DailyV2RY
      type: v2ray
      method: telegram
    - url: https://t.me/s/yaney_01
      type: v2ray
      method: telegram
    - url: https://t.me/s/FreakConfig
      type: v2ray
      method: telegram
    - url: https://t.me/s/ServerNett
      type: v2ray
      method: telegram
    - url: https://t.me/s/proxystore11
      type: v2ray
      method: telegram
    - url: https://t.me/s/custom_14
      type: v2ray
      method: telegram
    - url: https://t.me/s/FreeVlessVpn
      type: v2ray
      method: telegram
    - url: https://t.me/s/V2rayNG3
      type: v2ray
      method: telegram
    - url: https://raw.githubusercontent.com/Vauth/node/main/Main
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/ss.txt
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/ssr.txt
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/trojan.txt
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vless.txt
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/Epodonios/v2ray-configs/main/Splitted-By-Protocol/vmess.txt
      type: v2ray
      method: base64
    - url: https://raw.githubusercontent.com/ALIILAPRO/v2rayNG-Config/main/sub.txt
      type: v2ray
      method: base64
    # - url: https://raw.githubusercontent.com/Misaka-blog/chromego_merge/main/sub/merged_proxies_new.yaml
    #   type: clash
    - url: https://raw.githubusercontent.com/ts-sf/fly/main/clash
      type: clash
    - url: https://raw.githubusercontent.com/ronghuaxueleng/get_v2/main/pub/combine.yaml
      type: clash
    # - url: https://raw.githubusercontent.com/NiceVPN123/NiceVPN/main/Clash.yaml
    #   type: clash
    - url: https://raw.githubusercontent.com/anaer/Sub/main/clash.yaml
      type: clash
    - url: https://clashe.eu.org/clash/proxies
      type: clash
    - url: https://proxy.crazygeeky.com/clash/proxies
      type: clash
    - url: https://proxypool.link/clash/proxies
      type: clash
    - url: https://proxypool1999.banyunxiaoxi.icu/clash/proxies
      type: clash
    - url: https://pxypool.131433.xyz/clash/proxies
      type: clash
  request_timeout: 10
  subconverter: https://subapi.cmliussss.net
  subconverter_config: https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/config/ACL4SSR_Online_Mini_MultiMode.ini
  delay_url_test: http://www.gstatic.com/generate_204
  limit: 1500
  delay_batch_test_size: 600
  max_concurrent_tests: 100
  clash_secret: ''
  clash_host: 127.0.0.1
  clash_ports: 9090
  delay_timeout_unit: 10
  ban:
    # - ä¸­å›½
    # - China
    - CN
    - ğŸ‡¨ğŸ‡³
    # - ç”µä¿¡
    # - ç§»åŠ¨
    # - è”é€š
  default_uuid: &default_uuid 88888888-8888-8888-8888-888888888888
  banned_words:
    - 5rOV6L2uIOi9ruWtkCDova4g57uDIOawlCDlip8gb25ndGFpd2Fu
  vmess_example:
    v: 2
    ps: ''
    add: 0.0.0.0
    port: 0
    aid: 0
    scy: auto
    net: tcp
    type: none
    tls: ''
    id: *default_uuid
  clash2vmess:
    name: ps
    server: add
    port: port
    uuid: id
    alterId: aid
    cipher: scy
    network: net
    servername: sni
  fake_ips:
    - 8.8.8.8
    - 8.8.4.4
    - 4.2.2.2
    - 4.2.2.1
    - 114.114.114.114
    - 127.0.0.1
    - 0.0.0.0
  fake_domains:
    - google.com
    - github.com
  abfwhite:
    urls:
      - https://raw.githubusercontent.com/privacy-protection-tools/dead-horse/master/anti-ad-white-list.txt
    extras:
      - reg.163.com
  adbfurls:
    - https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/adservers.txt
    - https://raw.githubusercontent.com/AdguardTeam/AdguardFilters/master/ChineseFilter/sections/adservers_firstparty.txt
    - https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_224_Chinese/filter.txt
    # - "https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt"
    # - "https://malware-filter.gitlab.io/malware-filter/urlhaus-filter-ag.txt"
    # - "https://raw.githubusercontent.com/banbendalao/ADgk/master/ADgk.txt"
    # - "https://raw.githubusercontent.com/hoshsadiq/adblock-nocoin-list/master/nocoin.txt"
    # - "https://anti-ad.net/adguard.txt"
    - https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt
    - https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock
    # - "https://raw.githubusercontent.com/Cats-Team/AdRules/main/dns.txt"
    # - "https://raw.githubusercontent.com/hagezi/dns-blocklists/main/adblock/light.txt"
    # - "https://raw.githubusercontent.com/uniartisan/adblock_list/master/adblock_lite.txt"
    - https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/DD-AD.txt
    # "- https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/domain.txt"
  name_map:
    â›” å¹¿å‘Šæ‹¦æˆª: adblock
    ğŸš€ é€‰æ‹©ä»£ç†: proxy
    ğŸŒ çªç ´é”åŒº: region
    DIRECT: direct
  categories:
    redir:
      - ->
      - ä¸­è½¬
      - OVERALL
    JP:
      - JP
      - Japan
      - æ—¥
      - ğŸ‡¯ğŸ‡µ
    US:
      - US
      - United States
      - ç¾
      - ğŸ‡ºğŸ‡¸
    CN:
      - CN
      - China
      - ä¸­å›½
      - ä¸Šæµ·
      - æµ™æ±Ÿ
      - å¹¿ä¸œ
      - æ·±åœ³
      - ğŸ‡¨ğŸ‡³
    HK:
      - HK
      - Hong Kong
      - æ¸¯
      - ğŸ‡­ğŸ‡°
    TW:
      - TW
      - Taiwan
      - å°
      - ğŸ‡¹ğŸ‡¼
    CA:
      - CA
      - Canada
      - åŠ æ‹¿å¤§
      - ğŸ‡¨ğŸ‡¦
    FR:
      - FR
      - French
      - æ³•
      - ğŸ‡«ğŸ‡·
    SG:
      - SG
      - Singapore
      - æ–°åŠ å¡
      - ç‹®åŸ
      - ğŸ‡¸ğŸ‡¬
    GB:
      - GB
      - UK
      - United Kindom
      - Britain
      - è‹±
      - ğŸ‡¬ğŸ‡§
    KR:
      - KR
      - Korea
      - éŸ©
      - ğŸ‡°ğŸ‡·
    RU:
      - RU
      - Russia
      - ä¿„
      - ğŸ‡·ğŸ‡º
    DE:
      - DE
      - Germany
      - å¾·
      - ğŸ‡©ğŸ‡ª
    SE:
      - SE
      - Sweden
      - ç‘å…¸
      - ğŸ‡¸ğŸ‡ª
    CH:
      - CH
      - Switzerland
      - ç‘å£«
      - ğŸ‡¨ğŸ‡­
    EE:
      - EE
      - Estonia
      - çˆ±æ²™å°¼äºš
      - ğŸ‡ªğŸ‡ª
  categories_disp:
    JP: ğŸ‡¯ğŸ‡µ æ—¥æœ¬
    US: ğŸ‡ºğŸ‡¸ ç¾å›½
    HK: ğŸ‡­ğŸ‡° é¦™æ¸¯
    TW: â” å°æ¹¾
    SG: ğŸ‡¸ğŸ‡¬ æ–°åŠ å¡
    CA: ğŸ‡¨ğŸ‡¦ åŠ æ‹¿å¤§
    FR: ğŸ‡«ğŸ‡· æ³•å›½
    GB: ğŸ‡¬ğŸ‡§ è‹±å›½
    KR: ğŸ‡°ğŸ‡· éŸ©å›½
    DE: ğŸ‡©ğŸ‡ª å¾·å›½
    CN: ğŸ‡¨ğŸ‡³ ä¸­å›½
    RU: ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯
    SE: ğŸ‡¸ğŸ‡ª ç‘å…¸
    CH: ğŸ‡¨ğŸ‡­ ç‘å£«
